default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  encoding: utf8
  username: shunya
  host: localhost

development:
  <<: *default
  database: advrial_development

test:
  <<: *default
  database: advrial_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

